# Generated by Django 3.1.4 on 2021-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pladat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
